In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/PS_20174392719_1491204439457_log.csv")
df.shape

(6362620, 11)

In [3]:
df.isnull().sum().sum()

np.int64(0)

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df["isFraud"].value_counts(normalize=True)

isFraud
0    0.998709
1    0.001291
Name: proportion, dtype: float64

In [6]:
is_merchant = df["nameDest"].str.startswith("M")
df.loc[is_merchant, ["oldbalanceDest", "newbalanceDest"]].describe()

       oldbalanceDest  newbalanceDest
count       2151495.0       2151495.0
mean              0.0             0.0
std               0.0             0.0
min               0.0             0.0
25%               0.0             0.0
50%               0.0             0.0
75%               0.0             0.0
max               0.0             0.0

In [7]:
df["type"].value_counts()

type
CASH_OUT    2237500
PAYMENT     2151495
CASH_IN     1399284
TRANSFER     532909
DEBIT         41432
Name: count, dtype: int64

In [8]:
pd.crosstab(df["isFlaggedFraud"], df["isFraud"])

isFraud               0     1
isFlaggedFraud
0               6354407  8197
1                     0    16